"""Rebuild handwriting webfonts with fonttools[woff]==4.66.1.

Run from any directory: python frontend/scripts/subset_handwriting.py
Original font sources are retained. Every original Unicode mapping, glyph
outline and advance width is verified before writing the generated CSS.
"""
from collections import Counter
from hashlib import sha256
from io import BytesIO
from pathlib import Path
import json

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'public/fonts/wanwei-handwriting.ttf'
OUTPUT = ROOT / 'public/fonts/chunks'


def unicode_ranges(points):
    spans = []
    for point in sorted(points):
        if spans and point == spans[-1][1] + 1:
            spans[-1][1] = point
        else:
            spans.append([point, point])
    return ','.join(f'U+{start:X}' if start == end else f'U+{start:X}-{end:X}' for start, end in spans)


def main():
    original = TTFont(SOURCE, recalcTimestamp=False)
    cmap = original.getBestCmap()
    # Prioritize the existing intro and its five public demo titles.
    intro = (ROOT / 'src/MemoryCollage.tsx').read_text(encoding='utf8')
    intro += '歌里有我散场以后凌晨三点的耳机夏天最后一首歌下一站再见回声在歌里遇见同路人'
    common = {point for point in range(32, 127) if point in cmap}
    common.update(ord(char) for char in intro if ord(char) in cmap and ord(char) > 127)
    counts = Counter(char for file in sorted((ROOT / 'src').glob('*.tsx'))
                     for char in file.read_text(encoding='utf8') if ord(char) in cmap)
    for char, _ in counts.most_common():
        if len(common) >= 384:
            break
        common.add(ord(char))
    remaining = sorted(set(cmap) - common)
    groups = [sorted(common)] + [remaining[start:start + 224] for start in range(0, len(remaining), 224)]
    OUTPUT.mkdir(parents=True, exist_ok=True)
    faces = []
    seen = set()
    sizes = []
    for index, points in enumerate(groups):
        font = TTFont(SOURCE, recalcTimestamp=False)
        options = subset.Options()
        options.name_IDs = ['*']
        options.name_languages = ['*']
        options.name_legacy = True
        options.glyph_names = True
        options.layout_features = ['*']
        worker = subset.Subsetter(options=options)
        worker.populate(unicodes=points)
        worker.subset(font)
        font.flavor = 'woff2'
        data = BytesIO()
        font.save(data)
        encoded = data.getvalue()
        checked = TTFont(BytesIO(encoded))
        checked_cmap = checked.getBestCmap()
        assert set(checked_cmap) == set(points), 'Unicode mapping changed'
        assert not seen.intersection(points), 'Overlapping Unicode ranges'
        seen.update(points)
        for point, glyph in checked_cmap.items():
            source_glyph = cmap[point]
            assert checked['hmtx'][glyph] == original['hmtx'][source_glyph], 'Advance width changed'
            before = original['glyf'][source_glyph].getCoordinates(original['glyf'])
            after = checked['glyf'][glyph].getCoordinates(checked['glyf'])
            assert before == after, f'Glyph outline changed at U+{point:X}'
        for metric in ['ascent', 'descent', 'lineGap']:
            assert getattr(checked['hhea'], metric) == getattr(original['hhea'], metric)
        name = f'wanwei-{index:02d}-{sha256(encoded).hexdigest()[:12]}.woff2'
        (OUTPUT / name).write_bytes(encoded)
        sizes.append(len(encoded))
        faces.append("@font-face {\n  font-family: 'Wanwei Handwriting';\n"
                     f"  src: url('/fonts/chunks/{name}') format('woff2');\n"
                     "  font-weight: 400;\n  font-style: normal;\n  font-display: swap;\n"
                     f"  unicode-range: {unicode_ranges(points)};\n}}\n")
    assert seen == set(cmap), 'Original characters missing'
    (ROOT / 'src/handwriting-font.css').write_text(
        '/* Generated by scripts/subset_handwriting.py. */\n' + '\n'.join(faces), encoding='utf8')
    print(json.dumps({'unicode_mappings': len(seen), 'chunks': len(groups),
                      'common_bytes': sizes[0], 'total_bytes': sum(sizes),
                      'outlines_widths_and_metrics': 'unchanged'}))


if __name__ == '__main__':
    main()
